version: 2
updates:
- package-ecosystem: gomod
  target-branch: cloudflare-v4
  directory: "/"
  schedule:
    interval: weekly
  ignore:
    - dependency-name: "*aws-sdk-go*"
- package-ecosystem: github-actions
  target-branch: cloudflare-v4
  directory: "/"
  schedule:
    interval: weekly
- package-ecosystem: docker
  target-branch: cloudflare-v4
  directory: "/"
  schedule:
    interval: weekly
